name: junior_tennis_organizer
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ">=2.17.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.5
  freezed_annotation: ^2.0.3
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_svg: ^1.1.0
  keyboard_dismisser: ^3.0.0
  dio: ^4.0.6
  retrofit: ^3.0.1+1
  logger: ^1.1.0
  money_formatter: ^0.0.3
  intl: ^0.17.0
  repo_annotation:
    git:
      url: https://github.com/alphaSoft99/repo_annotation.git
  cached_network_image: ^3.2.1
  #  flash: ^2.0.5
  connectivity: ^3.0.6
  equatable: ^2.0.3
  package_info_plus: ^1.4.2
  pub_semver: ^2.1.1
  table_calendar: ^3.0.6
  animate_do: ^2.1.0
  launch_review: ^3.0.1
  notification_permissions: ^0.6.1
  keyboard_actions: ^4.0.1
  easy_localization: ^3.0.2-dev
  sms_autofill: ^2.2.0
  #firebase_messaging: ^13.1.0
  #firebase_core: ^1.19.1
  url_launcher: ^6.1.4
  shimmer:
    git:
      url: https://github.com/alphaSoft99/flutter_shimmer
  device_info_plus:
  geolocator: ^8.2.0
  smooth_page_indicator: ^1.0.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.0.3+1
  build_runner: any
  bloc_test: ^9.0.3
  hive_generator: ^1.1.3
  retrofit_generator: any
  platform: ^3.1.0
  mockito: ^5.2.0
  repo_generation:
    git:
      url: https://github.com/alphaSoft99/repo_generation.git

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/locale/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 700
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

    - family: FiraSans
      fonts:
        - asset: assets/fonts/FiraSans-Bold.ttf
          weight: 800